### ISSUE TITLE
原版clash和meta都能在alpine里直接运行，求大佬编译一版。

### ISSUE THREAD

**Issue by tonebean** [QingNetwork/tpclash#9]
参数：
CGO_ENABLE: 0

**Comment by j33h22** [comment]
Dear [tonebean](https://github.com/tonebean),

  Your issue i am noticed. 

  Because of your Linux distribution is musl-based,So I disable CGO in [TPClash v0.1.21](https://github.com/QingNetwork/tpclash/releases/tag/v0.1.21).

  Hope you can continue support this project.

Best regards,
Ju33Huang22
